[package]
name = "ngr"
version = "0.1.0"
authors = ["AR"]
edition = "2018"

[dependencies]
hmac-sha256 = "*"

[lib]
name = "ngr"
path = "src/lib.rs"

[[bin]]
name = "enb"
path = "src/enb/main.rs"

[[bin]]
name = "gnb"
path = "src/gnb/main.rs"