[package]
name = "enb"
version = "0.1.0"
authors = ["Austin Aigbe <eshikafe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ts = {path = "../ts"}

[[bin]]
name = "enb"
path = "src/main.rs"
